Repository Financial-Times/origami-image-set-tools, pull requests merged in 2021-03, with the labels that each got.

#270 use pull_request_target and not pull_request for the safe workflows
  .github/workflows/add-new-issues-and-pull-requests-to-origami-project-board.yml
  .github/workflows/apply-labels.yml
  .github/workflows/auto-approve.yml
  .github/workflows/sync-repo-labels.yml
Labels: cli, release:patch

#265 [Snyk] Security upgrade lodash from 4.17.20 to 4.17.21
  package-lock.json
  package.json
Labels: cli

#275 build(deps): npm audit fix
  package-lock.json
Labels: cli, dependencies, security
